name: Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/*'

jobs:
  test:
    defaults:
        run:
          working-directory: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm test
